author:
  name: Fight Club
  role: PhD in Philo Pastry
  bio:  K back to the front.
  location: London, France

social:
  - id: "x"
    label: "X"
    href: "#_"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/roicort"
  - id: "linkedin"
    label: "Linkedin"
    href: "#_"
  - id: "email"
    label: "Email"
    href: "mailto:"